version: "3"
services:
  pemweb_p_4:
    build: ./php
    image: pemweb_p_4_php:latest
    container_name: pemweb_p_4
    hostname: "project-akhir"
    volumes:
      - ./src:/var/www/html
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    working_dir: /var/www/html

  nginx_pemweb_p_4:
    build: ./nginx
    image: nginx_pemweb_p_4:latest
    container_name: nginx_pemweb_p_4
    hostname: "nginx_pemweb_p_4"
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - pemweb_p_4